import test from 'node:test';
import assert from 'node:assert/strict';
import { ArcGISClient } from '../src/arcgis.js';
import { OpenMeteoClient, currentVelocityToKnots, parseMarineResponse, parseUtcTimestamp, parseWeatherResponse, wmoWeatherText } from '../src/openmeteo.js';

const hours = ['2026-08-05T11:00','2026-08-05T12:00','2026-08-05T13:00','2026-08-06T12:00','2026-08-06T13:00'];
const weather = { latitude: 38.1, longitude: -20.1, current: { time: '2026-08-05T12:00', temperature_2m: 22, apparent_temperature: 24, relative_humidity_2m: 70, precipitation: 1, weather_code: 2, cloud_cover: 40, pressure_msl: 1012, visibility: 9000, wind_speed_10m: 12, wind_direction_10m: 270, wind_gusts_10m: 20 }, hourly: { time: hours, precipitation: [9,1,null,3,99], visibility: [1,8000,5000,7000,1], wind_speed_10m: [1,12,15,20,99], wind_gusts_10m: [1,20,25,30,99] } };
const marine = { latitude: 38.2, longitude: -20.2, current_units: { ocean_current_velocity: 'km/h' }, hourly_units: { ocean_current_velocity: 'm/s' }, current: { time: '2026-08-05T12:00Z', wave_height: 2, wave_direction: 300, wave_period: 8, wind_wave_height: 1, wind_wave_direction: 280, wind_wave_period: 4, swell_wave_height: 1.5, swell_wave_direction: 310, swell_wave_period: 10, sea_surface_temperature: 19, ocean_current_velocity: 3.6, ocean_current_direction: 90, sea_level_height_msl: .2 }, hourly: { time: hours, wave_height: [9,2,3,4,99], swell_wave_height: [9,1,2,3,99], ocean_current_velocity: [9,1,2,3,99] } };

test('parses UTC timestamps without trailing Z', () => assert.equal(parseUtcTimestamp('2026-08-05T12:00').toISOString(), '2026-08-05T12:00:00.000Z'));
test('maps WMO weather codes concisely', () => { assert.equal(wmoWeatherText(0), 'Clear'); assert.equal(wmoWeatherText(1), 'Mainly clear'); assert.equal(wmoWeatherText(2), 'Partly cloudy'); assert.equal(wmoWeatherText(3), 'Overcast'); assert.equal(wmoWeatherText(45), 'Fog'); assert.equal(wmoWeatherText(53), 'Drizzle'); assert.equal(wmoWeatherText(61), 'Rain showers'); assert.equal(wmoWeatherText(71), 'Snow'); assert.equal(wmoWeatherText(85), 'Snow showers'); assert.equal(wmoWeatherText(95), 'Thunderstorm'); });
test('parses weather response and converts visibility to kilometres', () => { const r = parseWeatherResponse(weather, 24); assert.equal(r.attributes.AirTempC, 22); assert.equal(r.attributes.WeatherText, 'Partly cloudy'); assert.equal(r.attributes.VisibilityKM, 9); assert.equal(r.attributes.WindFromDeg, 270); });
test('calculates aligned weather 24-hour summary', () => { const a = parseWeatherResponse(weather, 24).attributes; assert.equal(a.MaxWind24Kn, 20); assert.equal(a.MaxGust24Kn, 30); assert.equal(a.MinVis24KM, 5); assert.equal(a.Precip24MM, 4); assert.equal(new Date(a.ForecastStart).toISOString(), '2026-08-05T12:00:00.000Z'); assert.equal(new Date(a.ForecastEnd).toISOString(), '2026-08-06T12:00:00.000Z'); });
test('converts current velocity units', () => { assert.ok(Math.abs(currentVelocityToKnots(10, 'km/h') - 5.399568) < 1e-5); assert.ok(Math.abs(currentVelocityToKnots(1, 'm/s') - 1.943844) < 1e-5); assert.ok(Math.abs(currentVelocityToKnots(10, 'mph') - 8.689762) < 1e-5); assert.equal(currentVelocityToKnots(7, 'kn'), 7); });
test('parses marine response and current direction toward semantics', () => { const a = parseMarineResponse(marine, 24).attributes; assert.equal(a.WaveHeightM, 2); assert.equal(a.WaveFromDeg, 300); assert.ok(Math.abs(a.CurrentKnots - 1.943844) < 1e-4); assert.equal(a.CurrentToDeg, 90); });
test('calculates aligned marine 24-hour maxima', () => { const a = parseMarineResponse(marine, 24).attributes; assert.equal(a.MaxWave24M, 4); assert.equal(a.MaxSwell24M, 3); assert.ok(Math.abs(a.MaxCurrent24Kn - 5.831533) < 1e-4); });
test('handles null and unavailable variables without inventing values', () => { const r = parseWeatherResponse({ current: { time: '2026-08-05T12:00', visibility: null }, hourly: { time: [] } }); assert.equal(r.attributes.VisibilityKM, null); assert.equal(parseMarineResponse({ current: {}, hourly: {} }).status, 'unavailable'); });
test('supports partial weather-only and marine-only success through upsert', async () => { const calls=[]; const client = Object.assign(Object.create(ArcGISClient.prototype), { config:{conditionsLayerId:5,targetMmsi:247999000}, conditionsWeatherAt:null, conditionsMarineAt:null, layerUrl:(id)=>`/${id}`, post:async (_u,_e,body)=>{calls.push(JSON.parse(body.get('features'))[0]); return {addResults:[{success:true,objectId:1}]};} }); await client.upsertConditions(pos(), parseWeatherResponse(weather), {status:'error',attributes:{}}); assert.equal(calls[0].attributes.WeatherStatus, 'ok'); await client.upsertConditions(pos(), {status:'error',attributes:{}}, parseMarineResponse(marine)); assert.equal(calls[1].attributes.MarineStatus, 'ok'); });
test('rejects stale weather and marine datasets', async () => { let attrs; const client = Object.assign(Object.create(ArcGISClient.prototype), { config:{conditionsLayerId:5,targetMmsi:247999000}, conditionsObjectId:1, conditionsWeatherAt:new Date('2026-08-06T00:00Z'), conditionsMarineAt:new Date('2026-08-06T00:00Z'), layerUrl:(id)=>`/${id}`, post:async (_u,_e,body)=>{attrs=JSON.parse(body.get('features'))[0].attributes; return {updateResults:[{success:true}]};} }); await client.upsertConditions(pos(), parseWeatherResponse(weather), parseMarineResponse(marine)); assert.equal(attrs.WeatherAt, undefined); assert.equal(attrs.MarineAt, undefined); });
test('throttles, skips stale vessel positions, and prevents overlap', async () => { const state={lastPosition:pos()}; let n=0; const c = new OpenMeteoClient({enableConditions:true,openMeteoRefreshSeconds:1800,openMeteoMaxPositionAgeSeconds:1,openMeteoForecastHours:24}, {}, state); c.refresh=async()=>{n++;}; await c.refreshIfDue(true); await c.refreshIfDue(false); assert.equal(n,1); state.lastPosition.lastAIS=new Date(Date.now()-5000); assert.equal((await c.refreshIfDue(true)).skipped,'stale-position'); c.inFlight=true; assert.equal((await c.refreshIfDue(true)).skipped,'in-flight'); });
function pos(){ return {mmsi:247999000,vesselName:'AMERIGO VESPUCCI',latitude:38,longitude:-20,lastAIS:new Date()}; }
